package com.rekahdo.goodshop.phone_service.feign.enums;

public enum UnresolvedReason {

	BUSINESS_PHONE_NOT_PROVIDED,
	BUSINESS_PHONE_NOT_VERIFIED,
	CONTACT_PERSON_PHONE_NOT_PROVIDED,
	CONTACT_PERSON_PHONE_NOT_VERIFIED,
	CONTACT_PERSON_EMERGENCY_PHONE_NOT_PROVIDED,
	CONTACT_PERSON_EMERGENCY_PHONE_NOT_VERIFIED,

}