package com.rekahdo.ecommerce.goodshop.enums;

public enum ErrorCode {

    USER_ID_NOT_FOUND_VIOLATION,
    USERNAME_NOT_FOUND_VIOLATION,
    USERNAME_EXIST_VIOLATION,
    PASSWORD_NOT_STRONG_ENOUGH_VIOLATION,
    SQL_INTEGRITY_CONSTRAINT_VIOLATION,
    NULL_VALUE_IN_FIELD_VIOLATION,
    ORPHANED_COLLECTION_REFERENCE_VIOLATION,
    INVALID_DATA_IN_FIELD_VIOLATION,
    LIST_EMPTY_VIOLATION,
    USER_NOT_AUTHORIZED_VIOLATION

}